SEED_RULES = [
    {
        "title": "ModuleNotFoundError：找不到模块",
        "error_type": "ModuleNotFoundError",
        "pattern_type": "regex",
        "pattern_value": r"ModuleNotFoundError:\s+No module named ['\"](.+?)['\"]",
        "example_query": "ModuleNotFoundError: No module named 'requests'",
        "explanation": "Python 在导入模块时没有在当前解释器环境中找到对应的包。",
        "common_causes": [
            "依赖包尚未安装到当前环境",
            "虚拟环境和运行解释器不是同一个",
            "模块名拼写错误，或包名与导入名不一致",
        ],
        "troubleshooting_steps": [
            "运行 pip show requests 或 pip list 确认依赖是否存在",
            "检查 IDE 或终端当前使用的 Python 解释器",
            "确认虚拟环境已激活，再重新执行命令",
        ],
        "solutions": [
            "pip install requests",
            "如果使用 poetry 或 conda，请在对应环境内安装依赖",
            "修正 import 语句中的模块拼写",
        ],
        "tags": ["Python", "Import", "环境问题"],
        "search_terms": ["模块找不到", "包未安装", "no module named", "import"],
    },
    {
        "title": "ImportError：导入失败",
        "error_type": "ImportError",
        "pattern_type": "regex",
        "pattern_value": r"ImportError:\s+cannot import name ['\"](.+?)['\"]",
        "example_query": "ImportError: cannot import name 'settings' from 'config'",
        "explanation": "目标对象不存在、循环导入或导入路径错误时，Python 会抛出导入失败异常。",
        "common_causes": [
            "尝试导入的名称没有在模块中暴露",
            "模块之间互相导入导致循环依赖",
            "本地文件名遮蔽了第三方包",
        ],
        "troubleshooting_steps": [
            "打开被导入模块，确认目标名称确实存在",
            "检查是否存在循环导入链路",
            "确认项目内没有同名文件覆盖标准库或第三方包",
        ],
        "solutions": [
            "改为从正确模块导入目标对象",
            "把共享逻辑抽到第三个模块，打断循环依赖",
            "重命名冲突文件并清理 __pycache__",
        ],
        "tags": ["Python", "Import", "依赖关系"],
        "search_terms": ["导入失败", "cannot import name", "循环导入", "importerror"],
    },
    {
        "title": "SyntaxError：语法错误",
        "error_type": "SyntaxError",
        "pattern_type": "contains",
        "pattern_value": "SyntaxError:",
        "example_query": "SyntaxError: invalid syntax",
        "explanation": "解释器在解析代码结构时发现了非法语法，代码尚未进入运行阶段。",
        "common_causes": [
            "漏写冒号、括号或引号",
            "把保留字用在错误的位置",
            "复制代码时混入不可见字符",
        ],
        "troubleshooting_steps": [
            "查看报错箭头指向的具体位置",
            "重点检查上一行是否存在括号、引号未闭合",
            "把局部代码粘到最小示例中逐步排查",
        ],
        "solutions": [
            "补齐缺失的符号，例如 : ) ] } 或引号",
            "避免在变量名中使用 Python 关键字",
            "删除异常字符后重新输入相关代码",
        ],
        "tags": ["Python", "语法", "基础错误"],
        "search_terms": ["语法错误", "invalid syntax", "括号没闭合", "syntaxerror"],
    },
    {
        "title": "IndentationError：缩进错误",
        "error_type": "IndentationError",
        "pattern_type": "contains",
        "pattern_value": "IndentationError:",
        "example_query": "IndentationError: unexpected indent",
        "explanation": "Python 用缩进表示代码块，缩进层级不一致或位置错误时会直接报错。",
        "common_causes": [
            "意外多缩进或少缩进一层",
            "Tab 与空格混用",
            "复制代码后缩进格式丢失",
        ],
        "troubleshooting_steps": [
            "打开编辑器显示空白字符，确认缩进长度",
            "检查同一代码块中的缩进是否完全一致",
            "统一将缩进转换为 4 个空格",
        ],
        "solutions": [
            "删除多余缩进并重新对齐代码块",
            "在编辑器中执行格式化或 Convert Indentation",
            "配置编辑器只使用空格缩进",
        ],
        "tags": ["Python", "语法", "缩进"],
        "search_terms": ["缩进错误", "unexpected indent", "unindent", "indentationerror"],
    },
    {
        "title": "TypeError：类型不匹配",
        "error_type": "TypeError",
        "pattern_type": "regex",
        "pattern_value": r"TypeError:\s+unsupported operand type\(s\) for .+",
        "example_query": "TypeError: unsupported operand type(s) for +: 'int' and 'str'",
        "explanation": "操作符两侧的数据类型不兼容，Python 无法自动完成运算。",
        "common_causes": [
            "字符串与数字直接相加或比较",
            "函数返回值类型和预期不一致",
            "数据经过输入框、接口后变成了字符串",
        ],
        "troubleshooting_steps": [
            "打印相关变量的 type() 和实际值",
            "回溯变量来源，确认何时发生类型变化",
            "在运算前做显式类型转换",
        ],
        "solutions": [
            "把字符串转成 int/float，或把数字转成 str 再拼接",
            "为函数和接口约定清晰的输入输出类型",
            "在关键边界增加校验逻辑",
        ],
        "tags": ["Python", "类型", "运行时错误"],
        "search_terms": ["类型不匹配", "unsupported operand type", "类型转换", "typeerror"],
    },
    {
        "title": "TypeError：缺少必填参数",
        "error_type": "TypeError",
        "pattern_type": "regex",
        "pattern_value": r"TypeError:\s+.+missing .+required positional argument",
        "example_query": "TypeError: greet() missing 1 required positional argument: 'name'",
        "explanation": "调用函数时缺少位置参数，函数签名与调用方式不一致。",
        "common_causes": [
            "函数调用时漏传参数",
            "实例方法定义缺少 self 或调用方式错误",
            "重构后函数签名变化但调用方未同步",
        ],
        "troubleshooting_steps": [
            "查看函数定义，核对必填参数列表",
            "检查方法是实例方法、类方法还是静态方法",
            "搜索所有调用处，确认参数数量和顺序",
        ],
        "solutions": [
            "补齐缺失的参数",
            "若参数可选，为其设置默认值",
            "修正方法定义中的 self 或 cls",
        ],
        "tags": ["Python", "函数", "参数"],
        "search_terms": ["缺少参数", "required positional argument", "函数调用", "typeerror"],
    },
    {
        "title": "NameError：变量未定义",
        "error_type": "NameError",
        "pattern_type": "regex",
        "pattern_value": r"NameError:\s+name ['\"](.+?)['\"] is not defined",
        "example_query": "NameError: name 'usernmae' is not defined",
        "explanation": "当前作用域中不存在这个变量或函数名，解释器无法解析该标识符。",
        "common_causes": [
            "变量名拼写错误",
            "变量定义位置在使用之后",
            "跨函数或跨文件访问了错误作用域中的名称",
        ],
        "troubleshooting_steps": [
            "检查报错名称与定义处是否完全一致",
            "确认变量在使用前已经赋值",
            "查看是否存在作用域问题，例如局部变量与全局变量混淆",
        ],
        "solutions": [
            "修正拼写错误",
            "把变量定义移动到使用之前",
            "按需通过参数、返回值或 import 传递数据",
        ],
        "tags": ["Python", "变量", "运行时错误"],
        "search_terms": ["变量未定义", "name is not defined", "拼写错误", "nameerror"],
    },
    {
        "title": "AttributeError：对象没有该属性",
        "error_type": "AttributeError",
        "pattern_type": "regex",
        "pattern_value": r"AttributeError:\s+['\"].+['\"] object has no attribute ['\"].+['\"]",
        "example_query": "AttributeError: 'list' object has no attribute 'items'",
        "explanation": "你访问了对象并不支持的属性或方法，常见于类型判断失误。",
        "common_causes": [
            "把 list、dict、str 等对象当成了另一种类型",
            "调用了不存在或拼写错误的方法名",
            "第三方库版本变化导致 API 不一致",
        ],
        "troubleshooting_steps": [
            "先打印对象的 type() 确认真实类型",
            "使用 dir(obj) 查看可用属性",
            "检查依赖库版本和官方文档是否一致",
        ],
        "solutions": [
            "改用该类型真正支持的方法",
            "在调用前增加类型判断或数据转换",
            "根据库版本调整代码实现",
        ],
        "tags": ["Python", "对象", "运行时错误"],
        "search_terms": ["没有该属性", "object has no attribute", "方法不存在", "attributeerror"],
    },
    {
        "title": "IndexError：索引越界",
        "error_type": "IndexError",
        "pattern_type": "contains",
        "pattern_value": "IndexError: list index out of range",
        "example_query": "IndexError: list index out of range",
        "explanation": "访问列表或元组时使用了不存在的索引位置。",
        "common_causes": [
            "列表为空却直接取第一个元素",
            "循环边界写错，访问到了 length 之外",
            "过滤后数据数量少于预期",
        ],
        "troubleshooting_steps": [
            "打印 len(list) 和当前索引值",
            "检查循环终止条件是否正确",
            "确认数据源为空时是否做了兜底处理",
        ],
        "solutions": [
            "在取值前先判断列表长度",
            "使用 for item in items 代替手写索引遍历",
            "为空场景添加默认值或提前返回",
        ],
        "tags": ["Python", "容器", "列表"],
        "search_terms": ["索引越界", "list index out of range", "数组越界", "indexerror"],
    },
    {
        "title": "KeyError：字典键不存在",
        "error_type": "KeyError",
        "pattern_type": "contains",
        "pattern_value": "KeyError:",
        "example_query": "KeyError: 'email'",
        "explanation": "使用字典取值时访问了不存在的键，Python 会直接抛出 KeyError。",
        "common_causes": [
            "上游数据缺少该字段",
            "键名拼写不一致",
            "把列表索引访问方式错误地用于字典",
        ],
        "troubleshooting_steps": [
            "打印 dict.keys() 检查真实键名",
            "确认接口或配置文件是否始终返回该字段",
            "检查大小写、下划线等拼写细节",
        ],
        "solutions": [
            "改用 dict.get('email') 提供默认值",
            "在访问前先判断键是否存在",
            "统一字段命名并补齐缺失数据",
        ],
        "tags": ["Python", "容器", "字典"],
        "search_terms": ["键不存在", "KeyError", "dict.get", "字典字段缺失"],
    },
    {
        "title": "ValueError：值格式不合法",
        "error_type": "ValueError",
        "pattern_type": "regex",
        "pattern_value": r"ValueError:\s+invalid literal for int\(\) with base 10",
        "example_query": "ValueError: invalid literal for int() with base 10: '12px'",
        "explanation": "传入的数据类型本身可接受，但具体值格式不符合当前操作要求。",
        "common_causes": [
            "把包含非数字字符的字符串转成 int",
            "表单输入没有做清洗",
            "接口返回值格式与预期不同",
        ],
        "troubleshooting_steps": [
            "打印原始输入值，确认是否含空格、单位或特殊字符",
            "在转换前先 strip() 并校验格式",
            "检查接口协议是否发生变化",
        ],
        "solutions": [
            "先清洗字符串，再执行类型转换",
            "对用户输入增加正则或 schema 校验",
            "为异常数据提供错误提示和兜底逻辑",
        ],
        "tags": ["Python", "类型", "数据清洗"],
        "search_terms": ["值错误", "invalid literal for int", "转换失败", "valueerror"],
    },
    {
        "title": "ZeroDivisionError：除数不能为 0",
        "error_type": "ZeroDivisionError",
        "pattern_type": "contains",
        "pattern_value": "ZeroDivisionError: division by zero",
        "example_query": "ZeroDivisionError: division by zero",
        "explanation": "除法运算中分母为 0，数学上无意义，因此 Python 会中断执行。",
        "common_causes": [
            "计算前没有校验分母",
            "统计数据为空时分母变成 0",
            "用户输入直接参与计算",
        ],
        "troubleshooting_steps": [
            "打印分子和分母，确认分母来源",
            "检查空列表、空结果集等边界情况",
            "为计算逻辑添加最小值保护",
        ],
        "solutions": [
            "在除法前判断 denominator != 0",
            "为空数据提供默认值或跳过计算",
            "对用户输入做范围限制",
        ],
        "tags": ["Python", "数学", "边界条件"],
        "search_terms": ["除零错误", "division by zero", "分母为0", "zerodivisionerror"],
    },
    {
        "title": "FileNotFoundError：文件不存在",
        "error_type": "FileNotFoundError",
        "pattern_type": "contains",
        "pattern_value": "FileNotFoundError:",
        "example_query": "FileNotFoundError: [Errno 2] No such file or directory: 'data.csv'",
        "explanation": "代码尝试读取的文件路径不存在，或当前工作目录与你预期不一致。",
        "common_causes": [
            "相对路径基准目录错误",
            "文件名或扩展名拼写错误",
            "文件尚未生成或已被移动",
        ],
        "troubleshooting_steps": [
            "打印 os.getcwd() 查看当前工作目录",
            "确认目标文件实际存在于磁盘",
            "把相对路径改成绝对路径进行验证",
        ],
        "solutions": [
            "修正文件路径或文件名",
            "在代码中使用 pathlib.Path 统一拼接路径",
            "在读取前增加文件存在性检查",
        ],
        "tags": ["Python", "文件", "路径"],
        "search_terms": ["文件不存在", "No such file or directory", "路径错误", "filenotfounderror"],
    },
    {
        "title": "PermissionError：权限不足",
        "error_type": "PermissionError",
        "pattern_type": "contains",
        "pattern_value": "PermissionError:",
        "example_query": "PermissionError: [Errno 13] Permission denied: 'report.xlsx'",
        "explanation": "当前进程没有权限读取、写入或删除目标文件，或文件被其他程序占用。",
        "common_causes": [
            "文件正在被 Excel、编辑器等程序占用",
            "目标目录没有写入权限",
            "尝试操作系统保护目录",
        ],
        "troubleshooting_steps": [
            "关闭占用该文件的其他程序",
            "检查文件和目录权限设置",
            "尝试将输出目录改到用户有权限的位置",
        ],
        "solutions": [
            "关闭占用程序后重试",
            "调整输出路径或提升权限",
            "避免把结果写入系统保护目录",
        ],
        "tags": ["Python", "文件", "权限"],
        "search_terms": ["权限不足", "Permission denied", "文件被占用", "permissionerror"],
    },
    {
        "title": "RecursionError：递归层级过深",
        "error_type": "RecursionError",
        "pattern_type": "contains",
        "pattern_value": "RecursionError:",
        "example_query": "RecursionError: maximum recursion depth exceeded",
        "explanation": "递归调用没有按预期收敛，函数反复调用自身直到超过解释器限制。",
        "common_causes": [
            "缺少终止条件",
            "终止条件永远无法满足",
            "递归问题本身更适合改写成循环",
        ],
        "troubleshooting_steps": [
            "确认递归函数是否存在清晰的 base case",
            "打印关键参数，观察是否逐步逼近终止条件",
            "评估是否可以改写为 while 或 for 循环",
        ],
        "solutions": [
            "补充或修正终止条件",
            "减少递归深度，必要时改成迭代实现",
            "仅在充分理解后才考虑提升递归上限",
        ],
        "tags": ["Python", "递归", "算法"],
        "search_terms": ["递归过深", "maximum recursion depth exceeded", "死递归", "recursionerror"],
    },
]
